### PR TITLE
Ariel

### PR DESCRIPTION
**Pull request by gleason9113**
Chat component now displays received messages from both players.

### CODE REVIEW

**Comment by sashetov** [comment]
chat works but the board isn't updating. maybe after merging cera's PR will fix this? im ok to approve

**Comment by sashetov** [comment]
when i say board isn't updating i mean that player 1 is moving and the player 2 board doesn't update

**Review by sashetov — APPROVED** [review]
looks alright to approve

**Comment by C3ra906** [comment]
Approved, please resolve conflicts and merge. Alex said your board wasn't behaving correctly so can you pull and make sure it's up to date before merging? Thanks!

**Comment by gleason9113** [comment]
Hmm.  What I'm seeing with the moves is that on the first move, P2's board doesn't update with P1's first move until P2 moves, at which point P2's board updates to the current state; moves thereafter behave as expected.  Is that what you're seeing?

**Comment by sashetov** [comment]
yes, that's what im seeing. i haven't looked deep into it but it may have to do with move_done event data not being used consistently in both tabs to update board state. it did use to work before this PR though.

**Comment by sashetov** [comment]
i tested it on the main branch too with cera's new PR, it might have nothing to do with your PR tbh. it also only does it on the first opponent move. after that the board state is synched.

**Comment by gleason9113** [comment]
Yeah.  Just looking at the console, it looks like on the first move, P2 doesn't receive a move_done from the server, even though P1 does.  On the P2 side, clicking on the square used by P1 triggers the error sequence for that circumstance, but the boardState is shown as empty in the console.  I don't understand why the first move wouldn't trigger the move_done event for both players but subsequent ones would, though.

**Comment by sashetov** [comment]
for a successful move the server always sends move_done on both sockets, so it might be an issue with setting the handler on time or something like that. the only time the server wont send move_done on both sockets is if there's an error condition

**Pull request closed without merging**
