### PR TITLE
Cera2

### PR DESCRIPTION
**Pull request by C3ra906**
Hey Ariel and Alex,

So we are correctly handling the error message from the server and marking only when we are allowed. You can now click directly on the board instead of using devtool commands to play the game. Devtool's console log should be displaying correct messages. Could you please review and let me know if you see any errors?

Couple of issues:
1) I still need to get player id info from the server (or from front end if there's a way) or at least know which player is the first player so I can assign them X or O. Can the server send me back who's the first player?

2) The board is not updating right after the board state is updated. I need to figure this out. The backend is getting the correctly updated board but the screen is like a step behind or finally upload after the next player clicks on empty square. I think I need to play around with useState but if you know what might be the problem, please let me know.

Thank you! Will be working on getting the board to update as soon as board state changes and will be working on error dialogue box for players next.

### CODE REVIEW

**Comment by C3ra906** [comment]
Actually, the two tabs are keeping different board states....:/ need to fix that

**Comment by sashetov** [comment]
aah ok one thing that I'm realizing about board state is that it would help you if i sent out notifications on both sockets from the server that move was done on successful move_done, similar to how opponentAvailable was done.

ill write up such a PR right now

**Comment by sashetov** [comment]
another small thing to fix before merge would be to use the correct symbol when updating board state. you should be able to get that from the board state you get from the server anyway. in fact any time you get board state from the server just use that to update your local board...

**Comment by sashetov** [comment]
i think this one is ok to merge but you may find #15 helpful in updating board state easily. it will send ok state to both sockets so if you set up the move_done listener to update state on OK status it will always be the correct state

**Comment by C3ra906** [comment]
> another small thing to fix before merge would be to use the correct symbol when updating board state. you should be able to get that from the board state you get from the server anyway. in fact any time you get board state from the server just use that to update your local board...

Ahh, that simplifies things a lot, thank you

**Comment by C3ra906** [comment]
The board state for both players are the same now : ) but the rendering is still having some issues with showing all symbols marked on the board for both players.

**Comment by C3ra906** [comment]
So turns out not marking in front end and just using the boardState's values passed back fixed the problem. There's still some delay issue that I need to figure out but glad we got the board on screen to look the same for both players. I need to clean out some of the codes but let me know if you find any bugs, thank you : )

**Review by sashetov — APPROVED** [review]
I tested it and it looks great.

I think its good to merge.

Do you have any remaining things you want to fix before merging?

**Comment by C3ra906** [comment]
Thanks Alex! I want to clean the code up a bit. Left in a hurry at the end of the session and just pushed it to save where I was.Sincerely,Cera OhOn Nov 20, 2022, at 10:02 PM, sashetov ***@***.***> wrote:﻿
@sashetov approved this pull request.

I tested it and it looks great.
I think its good to merge.
Do you have any remaining things you want to fix before merging?

**Comment by C3ra906** [comment]
@sashetov I'm having an issue with move_done emit from the backend. Sometimes it will have data.data.gameWinner information and sometimes it will not and it's making my code fail when I assign data.data.gameWinner to the variable win when there is no gameWinner variable. Could we change that? The user message board and error code catching were working before but now they fail depending on which move_done emit I'm getting. Can we call the player socket emits in lines 276 and 277 of index.js changed to another name besides move_done or have data.gameWinner variable for all move_done emits? I think that should fix the problem on my end : )

**Comment by sashetov** [comment]
@C3ra906 move_done will have both boardState and gameWinner info in the data portion if the status is OK.
If you have an error case, you won't get them.
In what cases is gameWinner missing? (is it missing or is it some non-good value?)
Can you give steps on how to reproduce that?

**Comment by C3ra906** [comment]
> @C3ra906 move_done will have both boardState and gameWinner info in the data portion if the status is OK. If you have an error case, you won't get them. In what cases is gameWinner missing? (is it missing or is it some non-good value?) Can you give steps on how to reproduce that?
@sashetov There should be a user message for every move (for both success and error) but it only shows for successful move and if someone wins. gameWinner is missing when there's error and Devtools says it can't read data.data.gameWinner because it's null. Your explanation actually helped a lot! Looks like I need to make sure gameWinner value is never looked at unless we are making successful moves. Need to make a few changes. Will try fixing it later today : ) thank you

**Comment by sashetov** [comment]
@C3ra906 yeah, that was the logic in my mind:
check status
if OK  use .data and its gameWinner and boardState
if not OK use message /errorCode

ill add this to the documentation when I get to writing it

**Comment by gleason9113** [comment]
Ran the code.  Question:  It looks like, based on the backend code, that the Board needs to send: 'move_id: <index>' along with the boardState on line 78 of Board.js in order for the server to correctly process the move, otherwise the check on line 217 of index.js (server) fails automatically.  Should this change be added?

**Comment by sashetov** [comment]
the server does not take boardState, it gives it. it needs move_id though to make the move

**Comment by C3ra906** [comment]
Fixed the issue! I literally just had to move one line of code to someplace else lol. @gleason9113 Do I have your approval to merge?

**Comment by gleason9113** [comment]
Approved

**Pull request merged**
