### PR TITLE
Ariel

### PR DESCRIPTION
**Pull request by gleason9113**
This is a relatively minor PR targeting code cleanup.

Changes:
Cleaned up Board component by removing unnecessary <btn> element in html.
Fixed issue with HTML file which caused a 404 error.
Fixed 404 favicon not found error.

### CODE REVIEW

**Comment by C3ra906** [comment]
Hey Ariel, where did you move the winner/tie check to? I don't see it in the code and console.log is no longer showing it. Otherwise looking good.

**Comment by gleason9113** [comment]
Oh, geez.  Yeah, per the discussion we had on Wed the winner/tie functionality was being moved to the backend.  So I removed it from here.  Also, my most recent commit added a testing environment.  Still need to learn how to write tests using Jest, of course.

**Comment by C3ra906** [comment]
> 
Ahh, got it. Thanks :D

**Comment by sashetov** [comment]
looks good, I think its ok to merge

**Comment by sashetov** [comment]
cera mentioned in discord she's ok with merging, so i think we have 2 approves and I'll merge

**Pull request merged**
