### PR TITLE
Cera2

### PR DESCRIPTION
**Pull request by C3ra906**
I got the basic buttons working and flipping from one page to another. A couple of things:

Sorry @gleason9113 , I ended up touching App.js and Container.js in multiple places while trying to figure stuff out. After we are done with coding, maybe you can recopy and paste the codes that are yours so they show up as yours and not mine. 

The home button is having issues with loading the correct screen when clicked because I'm calling Container. Might need to get gameid and player name to ensure the home button takes you back to same game or something similar?

TODO: debug, add more content, form submission, replay button, show player id on screen. 
11/24 UPDATE: Simple Reset/replay button set up, form submission info in console.log. Still need to figure out Home navigation

Let me know if you notice any errors and bugs. Thank you and happy thanksgiving!

### CODE REVIEW

**Comment by C3ra906** [comment]
@sashetov Hey Alex, hope you had a good thanksgiving! 

When you get the chance, can you change your logic for tied game in index.js lines 163-171? The logic should be ==! not ===. 

Also, if you could emit both player's names and game id to the front end I can use that to figure out which player is whom and perhaps fix the issue I have with home button leading back to the splash page? Also, if players try to log back in from the splash page after pressing the Home button, the two tabs don't connect anymore (will always be waiting for an opponent). 

I would like to implement a reset button that basically emits to backend to set all the boardState to ' ' again since the backend has the control of the board and reset all variables on front-end side. Let me know if that makes sense to do.

**Comment by C3ra906** [comment]
Caught a bug:
x   o   x  o  o   x _ _ x isn't recognized as a win

**Comment by sashetov** [comment]
how would that be a win? don't you need to actually have 3 in a row?

**Comment by sashetov** [comment]
> When you get the chance, can you change your logic for tied game in index.js lines 163-171? The logic should be ==! not ===.


good catch. will commit fix directly to master

**Comment by sashetov** [comment]
the draw condition should be fixed now

**Comment by sashetov** [comment]
fixed bug for win condition not detected in rightmost column. good catch

**Comment by C3ra906** [comment]
That is supposed to be:X O XO O X        XVertical win for X ? Sorry if I was confusing late night Sincerely,Cera OhOn Nov 25, 2022, at 11:00 AM, sashetov ***@***.***> wrote:﻿
how would that be a win? don't you need to actually have 3 in a row?

**Comment by C3ra906** [comment]
Oh you got it, ignore what I just said lol Thanks for fixing them! :D Sincerely,Cera OhOn Nov 25, 2022, at 11:06 AM, sashetov ***@***.***> wrote:﻿
fixed bug for win condition not detected in rightmost column. good catch

**Review by sashetov — APPROVED** [review]
looks ok to approve, unless you need particular feedback on something

**Pull request merged**
