### PR TITLE
Ariel

### PR DESCRIPTION
**Pull request by gleason9113**
Okay, freshly tested, runs on my machine.  Also removed the Splash.js component - unused.  

If this is still not working on your machines, I will need some help with troubleshooting the code - this weekend, maybe?

### CODE REVIEW

**Review by C3ra906 — APPROVED** [review]
So I had the same error again (blank screen), but fixed it by removing { } around io from 
`import { io } from 'socket.io-client'; `
in socket.js. Not sure why the {} brackets were causing errors on mine but not on yours. 

The login page smoothly transitions to the board nice job : ) we should probably merge yours before merging mine, or merge yours and close mine and I can just do what I was doing in mine on the newly merged files? Whichever you and @sashetov  think is the best. I would love for us to go over the codes together over the weekend if you two have time.

**Comment by gleason9113** [comment]
Huh.  I'll try updating that.  Apologies for the confusion and thank you for taking a 2nd look!

Meeting this weekend sounds good to me- I can do Sat or Sun, pretty much any time either day.

**Comment by sashetov** [comment]
I can't this weekend but can tomorrow evening

**Review by sashetov — APPROVED** [review]
the bug i reported earlier looks like its fixed and fetching /join is implemented

**Comment by sashetov** [comment]
there are still issues with making moves and checking if making moves is valid but looks good otherwise to merge

**Pull request merged**
